services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    network_mode: host
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Watcher to reload Caddy when Caddyfile changes
  caddy-reloader:
    image: docker:cli
    restart: unless-stopped
    working_dir: /workdir
    volumes:
      - ./Caddyfile:/watch/Caddyfile:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/workdir:ro
    entrypoint: /bin/sh
    command:
      - -c
      - |
        apk add --no-cache inotify-tools
        echo 'Caddy reloader started, watching for changes...'
        while true; do
          inotifywait -e modify,create,close_write,moved_to /watch/Caddyfile 2>/dev/null
          sleep 1
          echo 'Caddyfile changed, reloading...'
          docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile --force 2>&1
          echo 'Reload complete'
        done
    network_mode: host
    depends_on:
      - caddy

volumes:
  caddy_data:
  caddy_config:
