services:
  caddy:
    # Use 'build' instead of 'image' to use the local Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    volumes:
      # Keep the Caddyfile mounted for the build/start to pick up the latest version
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    # Keep network_mode: host for simplicity, as the API call is now internal (localhost)
    network_mode: host
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:2019/metrics",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  caddy_data:
  caddy_config:
